[tools]
ruby = "3.2.2"
"aqua:nektos/act" = "latest"

[tasks.setup]
description = "Install dependencies"
run = "bundle install"
sources = ["Gemfile", ".mise.toml"]
outputs = ["Gemfile.lock"]

[tasks.build]
description = "Build the site"
depends = ["setup", "tailwindcss:build"]
env.JEKYLL_ENV = "production"
env.JEKYLL_MINIBUNDLE_MODE = "production"
run = "bundle exec jekyll build"

[tasks.server]
alias = ["dev"]
description = "Start the development server"
run = [{ tasks = ["tailwindcss:watch", "jekyll:serve"] }]

[tasks.jekyll]
hide = true
depends = ["setup"]
run = "bundle exec jekyll"

[tasks."jekyll:serve"]
hide = true
run = [{ task = "jekyll", args = ["serve", "--watch", "--livereload"] }]

[tasks.tailwindcss]
description = "Run tailwindcss-cli tasks"
depends = ["setup"]
run = "bundle exec tailwindcss --input=_assets/stylesheets/application.css --output=_tmp/tailwind.css"

[tasks."tailwindcss:build"]
hide = true
run = [{ task = "tailwindcss", args = ["--minify"] }]

[tasks."tailwindcss:watch"]
hide = true
run = [{ task = "tailwindcss", args = ["--watch"] }]

[tasks."lint:ruby"]
depends = ["setup"]
hide = true
run = "bundle exec rubocop"

[tasks."lint:html"]
depends = ["setup"]
hide = true
run = "bundle exec htmlproofer _site --check-sri"

[tasks."config:get"]
hide = true
quiet = true
run = """
#!/usr/bin/env ruby -ryaml

data = YAML.load_file("_config.yml")

ARGV.each do |arg|
  print "#{arg}: " unless ARGV.one?
  puts data.dig(*arg.split("."))
end
"""

[tasks.lint]
description = "Lint the source code"
depends = ["lint:html", "lint:ruby"]
