services:
  web:
    command: mise run server --host=0.0.0.0
    build:
      context: .
      target: base
    volumes:
      - .:/code
      - mise_data:/mise
      - node_modules:/code/node_modules
    ports:
      - 4000:4000
      - 35729:35729

volumes:
  mise_data:
  node_modules:
