version: "3"

volumes:
  ruby_gems:
  node_modules:

x-default: &default
  build:
    context: .
    target: base
  volumes:
    - .:${PWD:-/web}
    - ruby_gems:/usr/local/bundle
    - node_modules:${PWD:-/web}/node_modules
  working_dir: ${PWD:-/web}

services:
  web:
    <<: *default
    command: rake setup:bundler jekyll:serve
    environment:
      JEKYLL_HOST: 0.0.0.0
    ports:
      - 4000:4000
      - 35729:35729
    depends_on:
      - css

  css:
    <<: *default
    command: rake setup:pnpm tailwindcss:watch
    tty: true
